#!/usr/local/bin/zsh
ping 8.8.8.8 | awk '{
                        if( $0 ~ /^Request.*/ ){
                                printf("\033[41;37m%s\033[m\n",$0)
                        } else {
                                printf("\033[32m%s\033[m\n",$0)
                        }
                }'
